In [5]:
import pandas as pd

df3= pd.DataFrame({'a':[1,2,3,4,5], 'b':[4,2,7,1,4]})
#沿着列的方向，对每一行比较最大值
df3.cummax(axis="columns")

   a  b
0  1  4
1  2  2
2  3  7
3  4  4
4  5  5

In [6]:
df3.cummax(axis="index")

   a  b
0  1  4
1  2  4
2  3  7
3  4  7
4  5  7

In [ ]:
_df = pd.DataFrame(data ={'a':[1,2,3,4,5], 'b':[4,2,7,1,4]})