In [2]:
import pandas as pd

df=pd.read_csv('data/employees.csv')
df.head()

,employee_id,first_name,last_name,email,phone_number,job_id,salary,commission_pct,manager_id,department_id
0,100,Steven,King,SKING,515.123.4567,AD_PRES,24000.0,NaN,NaN,90.0
1,101,N_ann,Kochhar,NKOCHHAR,515.123.4568,AD_VP,17000.0,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,AD_VP,17000.0,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,IT_PROG,9000.0,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,IT_PROG,6000.0,NaN,103.0,60.0

In [3]:
df.describe()
#只查看数值项

       employee_id        salary  commission_pct  manager_id  department_id
count   107.000000    107.000000       35.000000  106.000000     106.000000
mean    153.000000   6461.682243        0.222857  124.764151      63.207547
std      31.032241   3909.365746        0.085184   20.315395      20.910110
min     100.000000   2100.000000        0.100000  100.000000      10.000000
25%     126.500000   3100.000000        0.150000  108.000000      50.000000
50%     153.000000   6200.000000        0.200000  122.000000      50.000000
75%     179.500000   8900.000000        0.300000  145.000000      80.000000
max     206.000000  24000.000000        0.400000  205.000000     110.000000

In [5]:
df.columns.tolist()

['employee_id',
 'first_name',
 'last_name',
 'email',
 'phone_number',
 'job_id',
 'salary',
 'commission_pct',
 'manager_id',
 'department_id']

In [6]:
#查找薪资最高 最低的员工信息
df[df["salary"]==df["salary"].min()]
# 布尔索引筛选

,employee_id,first_name,last_name,email,phone_number,job_id,salary,commission_pct,manager_id,department_id
32,132,TJ,Olson,TJOLSON,650.124.8234,ST_CLERK,2100.0,NaN,121.0,50.0

In [7]:
df.loc[df["salary"]==df["salary"].min()]

,employee_id,first_name,last_name,email,phone_number,job_id,salary,commission_pct,manager_id,department_id
32,132,TJ,Olson,TJOLSON,650.124.8234,ST_CLERK,2100.0,NaN,121.0,50.0

In [12]:
df.sort_values("salary").head(1)

,employee_id,first_name,last_name,email,phone_number,job_id,salary,commission_pct,manager_id,department_id
32,132,TJ,Olson,TJOLSON,650.124.8234,ST_CLERK,2100.0,NaN,121.0,50.0

In [13]:
df.sort_values("salary",ascending=False).head(1)

,employee_id,first_name,last_name,email,phone_number,job_id,salary,commission_pct,manager_id,department_id
0,100,Steven,King,SKING,515.123.4567,AD_PRES,24000.0,NaN,NaN,90.0